### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by webflo** [moll/capistrano-rsync#1]
I have read the documentation but still can not get to work? Can you create a sample configuration?

Thanks!

**Comment by moll** [comment]
Hey,

Sorry to hear you're having troubles. Sure, I can do that when I get behind a computer, but till then, have far did you get to?

**Comment by moll** [comment]
I copied this `Capfile` from an app of mine. Please let me know if that helps:

``` ruby
require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/rsync"

set :application, "foo"
set :stage, :production
set :deploy_to, "/var/www/foo"
set :repo_url, "."

role :app, "user@foo"

set :rsync_options, %w[--recursive --delete --delete-excluded  --exclude .git*]
```

**Comment by rromerogar** [comment]
Hi @moll ,

I have read the documentation but still can not get to work too

On my Capfile

``` ruby
# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'
require 'capistrano/rsync'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }
```

On my deploy.rb:

``` ruby
set :application, 'IRMAP'

set :scm, :rsync
set :rsync_options, %w[--recursive --delete --delete-excluded --exclude .git*]
set :deploy_to, '/home/campus/rubyHome/apps/IRMAP'


namespace :deploy do
  desc 'Restart application'
  task :restart do
    on roles(:app), in: :sequence, wait: 5 do
      # Your restart mechanism here, for example:
      execute :touch, release_path.join('tmp/restart.txt')
    end
  end

  after :restart, :clear_cache do
    on roles(:web), in: :groups, limit: 3, wait: 10 do
      # Here we can do anything such as:
      within release_path do
        execute :rake, 'cache:clear'
      end
    end
  end

  after :finishing, 'deploy:cleanup'
end
```

it makes a tmp/deploy git clone at local machine but seems that doesn't do a rsync from this tmp/deploy to /home/campus/rubyHome/apps/IRMAP/shared/deploy in remote mechine.... any suggestion?

**Comment by moll** [comment]
I might have a feeling it's related to the `scm` line. You could try setting it to `:git` or removing it as it'll default to `:git` anyways.

**Comment by rromerogar** [comment]
Thanks @moll 

If I put :git on :scm line, when I do a cap deploy, Capistrano tries to make a git clone on server side, that's what I want to avoid (I haven't git on server).

**Comment by webflo** [comment]
@moll thanks for your example. Have not tried it yet. But i had the same problem as @rromerogar ...

**Comment by rromerogar** [comment]
If I set :scm to git, then execute: cap test rsync , It's make shared/deploy on remote server. Then, change :scm to rsync, and then execute cap test deploy, and...works... :expressionless:

**Comment by moll** [comment]
Thanks for the feedback, fellows, and sorry for the troubles! I'll take a deeper look at everything tonight.

**Comment by webflo** [comment]
@rromerogar Please look at my pull request and try it out ...

**Comment by garthenweb** [comment]
I had the same Problems. The pull request ist working for me, please merge into master!

**Comment by estahn** [comment]
Is this gem working for anyone?

```
capistrano (3.2.1)
capistrano-rsync (1.0.2)
```

**Comment by fazy** [comment]
@estahn it didn't work for me without some changes. The following Capfile seems to be the minimum config (note, for testing purposes I only have this Capfile and be sure to clean out the tmp/ directory while debugging):

```
# Capfile

require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/rsync"

set :application, "foo"
set :stage, :production
set :deploy_to, "/var/www/foo"
set :repo_url, "git@foo:foo/foo.git"
set :keep_releases, 5
set :branch, "master"

role :app, "deploy@foo"

set :rsync_options, %w[--recursive --delete --delete-excluded  --exclude .git*]

set :scm, :rsync

namespace :rsync do
  task :set_current_revision do
    # nothing
  end
end
```

Regarding the set_current_revision: this seems to be needed now, but I didn't manage to make a working implementation that populates it properly. See Capistrano's [git.rake](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/tasks/git.rake#L71) if you want to try this.

**Comment by yourtallness** [comment]
Personally I can't get a rails application to deploy fully.

Firstly, the script does not create a shared/config/deploy on the target machine and fails, so I had to create it manually.

Secondly, rsync does not copy over many folders and directories, including /app, the Gemfile, etc. It only copies /vendor and some other stuff.

I have no idea why it just does not copy the entire cached repo...

**Comment by mtchavez** [comment]
It appears this gem is not being updated anymore and that a handful of people trying to use it are unable to get it to work. I browsed through the forks and found this one https://github.com/nifty/capistrano-rsync to be comprehensive and is better integrated with Capistrano 3. I thought I would share here in case people are banging their heads trying to get things working. Hope this helps.

**Comment by webflo** [comment]
Thanks all, i use https://github.com/Bladrak/capistrano-rsync these days.
