### ISSUE TITLE
SSH options & bundle

### ISSUE THREAD

**Issue by JLeech** [moll/capistrano-rsync#14]
Hello! I read README file and all questions below, but answers do not solve mine.
So I have to connect to remote server via SSH(the same server, in example), so i use standard capistrano form for sending USER and PASSWORD information, like this:

``` ruby
server '127.0.0.1', user: 'user', password: 'qwerty', roles: %w{web app} 
```

It asks me to enter password everytime, but it is in the line! At the same time, it knows username, and type it in the console. Cant solve this.

In README you marked, that "Deploy with Rsync to your server from any local (or remote) repository when using Capistrano. "
So i would like to deploy from local repository.
Here is my minimalistic `deploy.rb`

``` ruby
lock '3.1.0'
set :deploy_flag,"--development"
set :repo_url, "/home/user/api"
set :rsync_options, %w[--recursive --delete --delete-excluded --exclude .git*]
set :scm, :rsync
set :rvm, '2.0.0-p247'
set :default_env, { rvm_bin_path: '~/.rvm/bin' }
set :deploy_to, "/home/user/rsync/"
```

It is test example. I do NOT have repository on GIT, so just pass path to `repo_url` 
I would like my project in api being beployed to rsync. Right folders appear in rsync, but subdirectories in release are empty, and gems from `'~/.rvm/bin'` are bundled.
I hope you understand what i would like to do, and i hope you help me;

**Comment by moll** [comment]
Hey,

Sorry for the delay in response. Just to clarify — you're talking about deploying from a folder that is not a Git repository, right? You might actually be better off not using Capistrano::Rsync in this case and just run `rsync` from your `Capfile` directly. I don't remember exactly which Capistrano task you were supposed to overwrite, but perhaps its README can shine some light on that.

**Comment by JLeech** [comment]
Hello,
Yeap, i just created capistrano tasks for that, so this question is closed;
From the first look i didnt find how to do local uploading in capistrano, so started to search for a gem;
So thanks you anyway;
