### ISSUE TITLE
Can this be used without a SCM?

### ISSUE THREAD

**Issue by dlip** [moll/capistrano-rsync#3]
I have a folder full of generated files I want to send to a server, can this be used to upload the files which are not committed to SCM?

Maybe extending the upload! command might be an option otherwise...

**Comment by moll** [comment]
Hey,

You could use just plain `rsync` for that. Add an extra task to your `Makefile` (or `Rakefile` or even `Capfile`) with an `rsync` invocation and you should be all set.

If you want it to be run together with your deploy task, then just append it to the `rsync` task in your `Capfile` with something like:

``` ruby
task :rsync do
  system "rsync --recursive my-folder my-host:/folder..."
end
```

If you want it to be precisely how Capitrano::Rsync does it, check https://github.com/moll/capistrano-rsync/blob/master/lib/capistrano/rsync.rb.

Let me know if that works for you.

**Comment by moll** [comment]
Oh, sorry, I might've misunderstood the question a bit. I thought you had something to sync in addition to the SCM'ed folder.

So, it should be possible indeed. Not yet conveniently, but you could try right now by setting `rsync_stage` to `.` and clearing the `rsync:stage` task:

``` ruby
Rake::Task["rsync:stage"].clear
```

Please try it out in a safe directory first. :)

**Comment by dlip** [comment]
I ended up using the first method to keep things simple. Thanks for you help!

**Comment by moll** [comment]
Glad to hear! Simplicity FTW.
