### ISSUE TITLE
Rsync unstaged files

### ISSUE THREAD

**Issue by dmp1ce** [moll/capistrano-rsync#4]
Is there a way to rsync all of the files from the repository?  In fact, I don't even want it to check the git remote at all, I just want to copy all of the files to the release.

**Comment by moll** [comment]
Hey. Umm, which way do you mean? Skip uploading files from your local repository to the server and copy stuff from a directory on the server to the release directory straight away? Or what do you mean by "git remote"? :)

**Comment by dmp1ce** [comment]
I want to do something like this `rsync /local/git_repo/ development_server:release_dir`    Is that how it already works?  Looking at the code, it looks like the gem tries to sync to a git branch and then rsync.  I just want to sync everything in my working directory to the remote server.

This is primarily for when I'm working locally with vagrant.  I just want to update the vagrant box with my changes before checking them into git.

**Comment by dmp1ce** [comment]
But I would also like to keep the normal Capistrano flow.  I know that I could create a custom capistrano task to move all of the files, which I have already done.

**Comment by moll** [comment]
Aah. Got it. It's not yet that convenient, but you could try setting `rsync_stage` to `.` and clearing the `rsync:stage` task:

``` ruby
Rake::Task["rsync:stage"].clear
```

This should skip the cloning/staging part and just upload the current directory.

**Comment by dmp1ce** [comment]
I'm not certain that I need this plugin because I had to change quite a bit.  This is what I had to add to my `config/deploy/vagrant.rb` file to get the rsync to copy directly to the release folder in vagrant:

``` ruby
set :rsync_stage, '.'
Rake::Task["rsync:stage"].clear
set :rsync_options, ["-av", "-e\"vagrant ssh --\""]
set :rsync_cache, nil

# Override rsync task
Rake::Task["rsync"].clear
desc "Stage and rsync to the server"
task :rsync => %w[rsync:stage] do
  roles(:all).each do |role|
    user = role.user + "@" if !role.user.nil?

    rsync = %w[rsync]
    rsync.concat fetch(:rsync_options)
    rsync << fetch(:rsync_stage) + "/"
    rsync << ":#{release_path}"

    Kernel.system *rsync.join(" ")
  end
end
```
