### ISSUE TITLE
Provide option to sync only certain folders

### ISSUE THREAD

**Issue by Mrono** [moll/capistrano-rsync#9]

**Comment by moll** [comment]
Hey!

Thanks for the suggestion! Do you mean sync only a limited set of folders after staging? Like ignore `public` and only sync `app`, for example?

Would regular Rsync options do what you're after? I gave a [small example in the README](https://github.com/moll/capistrano-rsync#exclude-files-from-being-deployed) for excluding, but including would be similar. The Rsync man-page has a lot of hints how to do so.

**Comment by Mrono** [comment]
Wow, I didn't even see this, sorry.  I actually ended up writing a custom deployment system to handle it using rsync and ignores.  You can close this

**Comment by moll** [comment]
Your wish is my command. :-)
